In [6]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [12]:
cpi = pd.read_excel("../data/raw/cpi.xlsx")
oni = pd.read_csv("../data/raw/oni.csv")

In [14]:
cpi

,baseyear,year,month_code,month,state,sector,group,subgroup,index,inflation,status
0,2012,2025,12,December,All India,Combined,Consumer Food Price,Consumer Food Price-Overall,201.1,-2.71,F
1,2012,2025,11,November,All India,Combined,Consumer Food Price,Consumer Food Price-Overall,201.6,-3.91,F
2,2012,2025,10,October,All India,Combined,Consumer Food Price,Consumer Food Price-Overall,200.5,-5.02,F
3,2012,2025,9,September,All India,Combined,Consumer Food Price,Consumer Food Price-Overall,201.0,-2.33,F
4,2012,2025,8,August,All India,Combined,Consumer Food Price,Consumer Food Price-Overall,202.1,-0.64,F
...,...,...,...,...,...,...,...,...,...,...,...
163,2012,2012,5,May,All India,Combined,Consumer Food Price,Consumer Food Price-Overall,98.4,9.70,F
164,2012,2012,4,April,All India,Combined,Consumer Food Price,Consumer Food Price-Overall,97.4,9.32,F
165,2012,2012,3,March,All India,Combined,Consumer Food Price,Consumer Food Price-Overall,95.2,7.09,F
166,2012,2012,2,February,All India,Combined,Consumer Food Price,Consumer Food Price-Overall,93.9,4.45,F
167,2012,2012,1,January,All India,Combined,Consumer Food Price,Consumer Food Price-Overall,93.4,-0.21,F

In [15]:
oni

,Date,ONI from CPC missing value -99.9 https://psl.noaa.gov/data/timeseries/month/
0,01-01-1950,-1.53
1,01-02-1950,-1.34
2,01-03-1950,-1.16
3,01-04-1950,-1.18
4,01-05-1950,-1.07
...,...,...
919,01-08-2026,-9999.00
920,01-09-2026,-9999.00
921,01-10-2026,-9999.00
922,01-11-2026,-9999.00
923,01-12-2026,-9999.00

In [17]:
print("CPI shape: ", cpi.shape, "\nONI shape: ", oni.shape)

CPI shape:  (168, 11)
ONI shape:  (924, 2)

In [18]:
cpi.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168 entries, 0 to 167
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   baseyear    168 non-null    int64
 1   year        168 non-null    int64
 2   month_code  168 non-null    int64
 3   month       168 non-null    object
 4   state       168 non-null    object
 5   sector      168 non-null    object
 6   group       168 non-null    object
 7   subgroup    168 non-null    object
 8   index       168 non-null    float64
 9   inflation   155 non-null    float64
 10  status      168 non-null    object
dtypes: float64(2), int64(3), object(6)
memory usage: 14.6+ KB

In [20]:
oni.rename(columns={'  ONI from CPC  missing value -99.9 https://psl.noaa.gov/data/timeseries/month/': "ONI"}, inplace=True)
oni.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 924 entries, 0 to 923
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    924 non-null    object
 1   ONI     924 non-null    float64
dtypes: float64(1), object(1)
memory usage: 14.6+ KB

In [21]:
cpi.describe()

       baseyear        year  month_code       index   inflation
count     168.0   168.00000  168.000000  168.000000  155.000000
mean     2012.0  2018.50000    6.500000  148.952976    5.121548
std         0.0     4.04318    3.462373   30.272075    3.916683
min      2012.0  2012.00000    1.000000   93.400000   -5.020000
25%      2012.0  2015.00000    3.750000  127.950000    2.090000
50%      2012.0  2018.50000    6.500000  139.550000    5.210000
75%      2012.0  2022.00000    9.250000  173.800000    8.560000
max      2012.0  2025.00000   12.000000  211.100000   14.190000

In [23]:
cpi.isna().sum()

baseyear       0
year           0
month_code     0
month          0
state          0
sector         0
group          0
subgroup       0
index          0
inflation     13
status         0
dtype: int64